version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:v2
    ports:
      - "8001:8000"
    volumes:
      - ./surreal_data/:/mydata
    command: start --user root --pass root rocksdb:/mydata/mydatabase.db
    pull_policy: always
    user: root

  open_notebook:
    image: lfnovo/open_notebook:latest
    ports:
      - "8080:8502"
    env_file:
      - docker.env
    depends_on:
      - surrealdb
    pull_policy: always
    volumes:
      - ./notebook_data:/app/data
      - ./transformations.yaml:/app/transformations.yaml
      - ./user:/app/prompts/patterns/user
